version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: ./web
    container_name: fastapi-web
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: ./worker
    container_name: sqs-worker
    depends_on:
      - localstack
      - redis
